// imports
import App from '@/App.vue'
import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowRotateLeft,
  faArrowUpRightFromSquare,
  faAtom,
  faBell,
  faBug,
  faBowlRice,
  faCalculator,
  faCameraRotate,
  faChartBar,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faClipboardCheck,
  faCircle,
  faClock,
  faCoins,
  faDatabase,
  faDice,
  faExclamationTriangle,
  faEye,
  faFaceSmile,
  faFlagCheckered,
  faFolderOpen,
  faForward,
  faGamepad,
  faGauge,
  faGears,
  faGlobe,
  faHourglass,
  faHouse,
  faIndustry,
  faInfoCircle,
  faKeyboard,
  faKhanda,
  faLink,
  faList,
  faLock,
  faMagnifyingGlass,
  faMedal,
  faMicroscope,
  faPencil,
  faPenNib,
  faPlay,
  faPlus,
  faPause,
  faPauseCircle,
  faPeopleGroup,
  faPlayCircle,
  faQuestion,
  faRandom,
  faRightLeft,
  faRobot,
  faRotateRight,
  faUnlink,
  faScrewdriverWrench,
  faSpinner,
  faSquarePlus,
  faTimeline,
  faTriangleExclamation,
  faTrophy,
  faTruck,
  faUpDownLeftRight,
  faUserTie,
  faWalkieTalkie,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import * as vueshortkey from 'vue3-shortkey'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import 'vuetify/styles'

// use fontawesome icons
library.add(
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowRotateLeft,
  faArrowUpRightFromSquare,
  faAtom,
  faBell,
  faBowlRice,
  faBug,
  faCalculator,
  faCameraRotate,
  faChartBar,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faClipboardCheck,
  faCircle,
  faClock,
  faCoins,
  faDatabase,
  faDice,
  faExclamationTriangle,
  faEye,
  faFaceSmile,
  faFlagCheckered,
  faFolderOpen,
  faForward,
  faGamepad,
  faGauge,
  faGears,
  faGlobe,
  faHourglass,
  faHouse,
  faIndustry,
  faInfoCircle,
  faKeyboard,
  faKhanda,
  faLink,
  faList,
  faLock,
  faMagnifyingGlass,
  faMedal,
  faMicroscope,
  faPencil,
  faPenNib,
  faPlay,
  faPlus,
  faPause,
  faPauseCircle,
  faPeopleGroup,
  faPlayCircle,
  faQuestion,
  faRandom,
  faRightLeft,
  faRobot,
  faRotateRight,
  faUnlink,
  faScrewdriverWrench,
  faSpinner,
  faSquarePlus,
  faTimeline,
  faTriangleExclamation,
  faTrophy,
  faTruck,
  faUpDownLeftRight,
  faUserTie,
  faWalkieTalkie,
  faXmark,
)

const app = createApp(App)

const vuetify = createVuetify({
  components,
  directives,
  theme: {
    defaultTheme: 'dark', 
  },
})

app.component('font-awesome-icon', FontAwesomeIcon)
app.use(createPinia())
app.use(vuetify) 
app.use(vueshortkey)
app.mount('#app')
